TRUNCATE TABLE investimentos;
TRUNCATE TABLE estados CASCADE;
TRUNCATE TABLE subfuncoes CASCADE;
TRUNCATE TABLE data_investimento CASCADE;

TRUNCATE TABLE ocorrencias;
TRUNCATE TABLE data_ocorrencia CASCADE;
TRUNCATE TABLE categorias CASCADE;
